### ISSUE TITLE
안녕하세요. 글 링크가 하나 비어있습니다.

### ISSUE THREAD

**Issue by SongYunSeop** [JoMingyu/Lets-Study#51]
![image](https://user-images.githubusercontent.com/11675853/225632121-5afe9a9f-47f0-49d0-80c4-52f7a4d65a74.png)

https://github.com/JoMingyu/Lets-Study/blob/master/README.md?plain=1#L1084

**Comment by JoMingyu** [comment]
f3ad3e0d1e96d604c22e6bcd713b206660b88996 에서 수정되었습니다.
