### ISSUE TITLE
안녕하세요. 글 제목이 또 하나 비어있습니다.

### ISSUE THREAD

**Issue by SongYunSeop** [JoMingyu/Lets-Study#52]
<img width="374" alt="image" src="https://github.com/JoMingyu/Lets-Study/assets/11675853/791fca2c-7107-406e-bd55-069583826b2d">

https://github.com/JoMingyu/Lets-Study/blob/master/README.md?plain=1#L1257

**Comment by JoMingyu** [comment]
수정됐습니다
