### ISSUE TITLE
다양한 주제 추가

### ISSUE THREAD

**Issue by Xsolute** [JoMingyu/Lets-Study#7]
여러가지에 관심 많은 사람들이 이 repo에 들리면서, 일부 주제만으로 공부하는 것보다는 다양한 주제를 접해보면서 체험해보는 것도 좋을 것 같습니다.
backend 주제 부근에 국한되지 않고, 여러가지 주제를 올리는 것도 괜찮을까요?

**Comment by JoMingyu** [comment]
네 제발용..
